import hashlib
import json
from pathlib import Path

import pytest

from TradingSystemLab import baseline_v2


def test_frozen_matrix_contract() -> None:
    assert len(baseline_v2.RUNS) == 24
    assert len(set(baseline_v2.RUNS)) == 24
    assert {row[0] for row in baseline_v2.RUNS} == {"T2", "T3"}
    assert {row[1] for row in baseline_v2.RUNS} == {"Si", "CNY", "GD", "BR", "MIX", "NG"}
    assert {row[2] for row in baseline_v2.RUNS} == {"M30", "H1"}
    assert baseline_v2.COST_MODEL == {"name": "C1", "ticks_per_side": 1,
                                      "round_trip_ticks": 2,
                                      "additional_slippage_ticks": 0}


def test_phase_exclusions_are_explicit() -> None:
    source = Path(baseline_v2.__file__).read_text(encoding="utf-8")
    for flag in ("optimization", "ranking", "selection", "walk_forward", "mtf"):
        assert f'"{flag}": False' in source


def test_frozen_strategy_hashes() -> None:
    root = Path("TradingSystemLab/strategies/trend")
    files = {"T2": "T2_Trend_Pullback.py", "T3": "T3_MTF_Trend.py"}
    actual = {key: hashlib.sha256((root / name).read_bytes()).hexdigest()
              for key, name in files.items()}
    assert actual == baseline_v2.STRATEGY_SHA256


def test_prefix_loader_never_reads_true_oos(tmp_path: Path) -> None:
    # Use the approved-root guard separately, then exercise the prefix primitive
    # used by the baseline against a sentinel malformed OOS row.
    source = tmp_path / "sample.csv"
    source.write_text("Datetime;Open;High;Low;Close\n"
                      "2024-12-31 22:00:00;1;2;0;1\n"
                      "2025-01-01 00:00:00;DO-NOT-PARSE\n", encoding="utf-8")
    loader = baseline_v2.DataLoader(forbid_true_oos=True)
    frame = loader.load_csv_prefix(source, start=baseline_v2.DEVELOPMENT_START,
                                   end_exclusive=baseline_v2.TRUE_OOS_START)
    assert len(frame) == 1
    assert frame.index.max() < baseline_v2.TRUE_OOS_START
    with pytest.raises(ValueError, match="UNAPPROVED"):
        baseline_v2._source(tmp_path, "Si", "M30")


def test_generated_manifest_is_auditable() -> None:
    path = Path("TradingSystemLab/results/baseline_v2/manifest.json")
    if not path.exists():
        pytest.skip("baseline execution artifact is generated by the Phase 1 runner")
    manifest = json.loads(path.read_text(encoding="utf-8"))
    assert manifest["run_count"] == 24
    assert len(manifest["declared_runs"]) == 24
    assert manifest["cost_models"] == [baseline_v2.COST_MODEL]
    assert manifest["frozen_strategy_hashes"] == baseline_v2.STRATEGY_SHA256
    for flag in ("optimization", "ranking", "selection", "walk_forward", "mtf"):
        assert manifest[flag] is False
    assert manifest["true_oos_blocked"] is True
